### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by CrossNox** [CrossNox/m2r2#17]
Hi everyone,
As you might know, `m2r2` is a fork of `m2r`. I forked it, fixed some code and deployed it to pypi out of personal need and lack of response on the original repo. Some people found it useful as well, so, here we are now.

Lately, I haven't got much time other than for university and work. PR #14 was stalled for no other reason than me not merging it, and I apologize. That got me thinking that I wouldn't like `m2r2` to suffer the same fate as it's predecessor. In order to remove the SPOF (me and my schedule) I'm opening this. 

Feel free to send me an email (in my profile) and let's talk. I don't think the project needs any crazy requirements tech-wise, so if you know some python, can work with other people and want to teach/learn stuff, you are most welcome.

**Comment by JWCook** [comment]
Hey @CrossNox, have you considered adding this project to [Code Shelter](https://www.codeshelter.co/)? This is pretty much exactly what it's for: when a project's author no longer has time for maintenance but there's still enough community interest to keep the project going.

Even if someone doesn't step up right away to work on this project specifically, users can ask for help from the other [maintainers](https://www.codeshelter.co/maintainers/) (via codeshelter.zulipchat.com) if, for example, there's an urgent bugfix to make or if a PR has been stuck for awhile.

**Comment by adrien-berchet** [comment]
Hi @CrossNox 
I can participate to basic maintenance if you are ok. I already proposed #69 and I would need it to be merged but I can also take some time to review a few other PRs.
Also, I couldn't find the project on Code Shelter, was it added there and then removed?
