### ISSUE TITLE
Conversion for markdown highlight

### ISSUE THREAD

**Issue by felipefoz** [CrossNox/m2r2#27]
Hi, 

I've been using python-semantic-release for generating the Changelog markdown files, but apparently m2r2 is not correctly converting to RST.
Example from Changelog.md
```
* Update setup.py ([`2513d97`](https://gitlab.com/felipe_public/badges gitlab/-/commit/2513d970f9b055675de2f5479856604a7774f430))
 ```
Result after m2r2 inclusion in sphinx
```
Update setup.py (``2513d97` <https://gitlab.com/felipe_public/badges-gitlab/-/commit/2513d970f9b055675de2f5479856604a7774f430>`_)
 ```

I believe insted of converting to double quotes (for .rst) it is missing the second double quotes?

Am I missing something?

Regards,

**Comment by CrossNox** [comment]
Hi, this seems to be related to #36 . RST does not allow for hyperlinks to be formatted.
Closing this as to centralize in a single issue.
