### ISSUE TITLE
Changes in arparse output breaks test for python3.10

### ISSUE THREAD

**Issue by parona-source** [CrossNox/m2r2#29]
There have been changes in argparse output https://bugs.python.org/issue9694 which breaks https://github.com/CrossNox/m2r2/blob/development/tests/test_cli.py#L61.
There is a pull request in m2r which updates it https://github.com/miyakogi/m2r/pull/62, it applies cleanly to m2r2. Ive tested with python3.9 and python3.10 with both passing tests.

**Comment by CrossNox** [comment]
Should be fixed in v0.3.1, pls let me know if you run into this issue still!
