### ISSUE TITLE
Duplicate explicit target name for links

### ISSUE THREAD

**Issue by matthieucan** [CrossNox/m2r2#30]
Hello,
When a markdown document contains more than 1 link whose name is identical, `m2r2` generates those links but fails to make them anonymous references.
According to https://github.com/sphinx-doc/sphinx/issues/3921 this doesn't follow ReST specs.

How to reproduce:

```shell
% cat foo.md
[foo](https://foo.bar)
[foo](https://bar.foo)
% m2r2 foo.md
% cat foo.rst

`foo <https://foo.bar>`_
`foo <https://bar.foo>`_
% rst2html.py foo.rst > /dev/null
foo.rst:3: (WARNING/2) Duplicate explicit target name: "foo".
```

**Comment by CrossNox** [comment]
Hello @matthieucan, I think you'd want to run as `m2r2 --anonymous-references foo.md` ?

**Comment by matthieucan** [comment]
Hi @CrossNox, thank you very much, that fixed my problem! :+1:

**Comment by ItsDrike** [comment]
How would I enable anonymous references when using `.. mdinclude` within another rst document?

**Comment by briantist** [comment]
For anyone else who had this issue and wondering how to set the value in `conf.py` when used with sphinx:

```python
m2r_anonymous_references = True
```

The sphinx option names can be seen here:
https://github.com/CrossNox/m2r2/blob/0408d7acea843485d9ff42ee08a105a79f045493/m2r2.py#L675C27-L675C51
