### ISSUE TITLE
v0.3.3 is incompatible with `sphinx-rtd-theme 1.0.0`

### ISSUE THREAD

**Issue by ReenigneArcher** [CrossNox/m2r2#55]
v0.3.3 is incompatible with `sphinx-rtd-theme 1.0.0`. Because of ReadTheDocs this is probably the most popular theme for sphinx.

```txt
The conflict is caused by:
    m2r2 0.3.3 depends on docutils>=0.19
    sphinx 5.1.1 depends on docutils<0.20 and >=0.14
    sphinx-rtd-theme 1.0.0 depends on docutils<0.18
```

**Comment by demberto** [comment]
That's not the only one, its even incompatible with `myst_parser`. Please consider downgrading to `0.18.0`.

**Comment by CrossNox** [comment]
Use v0.3.2

**Comment by ReenigneArcher** [comment]
> Use v0.3.2

Of course, no other option for now.

Could you not incorporate some logic to handle using an older version of `docutils`?

**Comment by ReenigneArcher** [comment]
> You could pin down a version of m2r2 in your build config by `m2r2==0.3.2`

That's exactly what I do. All my projects are failing on the dependabot update.

Example: https://github.com/LizardByte/Sunshine/pull/327

> There's nothing than can be done

Of course there is. It's quite easy to handle import logic... `try/except/else/finally` or `if/else`.

Untested, but this should do the trick.

```py
import mistune
from docutils import io, nodes, statemachine, utils
from docutils.parsers import rst
from docutils.utils import column_width
from pkg_resources import get_distribution

try:
    ErrorString = io.error_string
except:
    from docutils.core import ErrorString

# use ErrorString in code below
```

Above code is based on this PR: https://github.com/CrossNox/m2r2/pull/49/files ... I don't know if there multiple PRs to handle the update of docutils to v0.19.

Since readthedocs is supporting python 2.7 still, it's unlikely they'll make v0.19 of docutils a requirement and probably instead stick with < 0.18.

**Comment by ReenigneArcher** [comment]
I see that there were two new versions for `0.3.3`. Is it possible to redact `0.3.3` from pypi in favor of the post2 version?

The original 0.3.3 is still installable under Python 2.7.
